### ISSUE TITLE
Won't work on CLI

### ISSUE THREAD

**Issue by neilsf** [bigfish-hu/payment-gateway-php-sdk#1]
If you try to send requests on a command line interface, the SDK will break at this line:

https://github.com/bigfish-hu/payment-gateway-php-sdk/blob/2bb9a316bbadb58d829216f4147f65c0d43f576a/src/BigFish/PaymentGateway.php#L750

I think this method should have a fallback return value if `$_SERVER['HTTP_HOST']` doesn't exist.

**Comment by viderspan** [comment]
Thank you for the comment. We will review and fix it.

**Comment by viderspan** [comment]
We fixed the bug in the SDK 2.10.1 version.
